### ISSUE TITLE
Sign up

### ISSUE THREAD

**Issue by lysa-thorn** [pnc-virtual-company/2020-G4-letsgo#1]
create a new account

**Comment by channakchhon** [comment]
The issue title is not clear.
What do you mean by all view?
You need to be specific. Break it down into small tasks such as login view, register view, dashboard view....

**Comment by lysa-thorn** [comment]
@channakchhon, could I change this task?

**Comment by channakchhon** [comment]
You rename the title

**Comment by borith23** [comment]
@channakchhon Sorry teacher I want to ask you do we just need email and password when we create a new account?
