### ISSUE TITLE
Create a project with authentication

### ISSUE THREAD

**Issue by lysa-thorn** [pnc-virtual-company/2020-G4-letsgo#4]
create a project and activate with authentication

**Comment by lysa-thorn** [comment]
@channakchhon, please review for authentication task

**Comment by channakchhon** [comment]
I don't see your commit link to any issue about project initialization.
This issue and commit you made not clearly much thing about authentication

**Comment by lysa-thorn** [comment]
@channakchhon because there are two commit so it will get the result of the last commit

**Comment by lysa-thorn** [comment]
@channakchhon How can I change to first commit?

**Comment by channakchhon** [comment]
It's ok. If you're sure about it.

**Comment by lysa-thorn** [comment]
Because I forgot to add task into the board by id of board. Could you check my first commit in authentication branch?

**Comment by channakchhon** [comment]
It's ok if your commit with issue number

**Comment by lysa-thorn** [comment]
@channakchhon Thank you so much.
