### ISSUE TITLE
Design databases

### ISSUE THREAD

**Issue by lysa-thorn** [pnc-virtual-company/2020-G4-letsgo#9]
draw tables relationship

**Comment by dalinStudent** [comment]
![1](https://user-images.githubusercontent.com/54297749/87105036-fed38200-c283-11ea-840b-89e3201dd08d.PNG)

**Comment by dalinStudent** [comment]
![1](https://user-images.githubusercontent.com/54297749/87105179-67bafa00-c284-11ea-9eb0-c3703959d27f.PNG)
